# Build the Go Binary.
FROM golang:1.19 as build_cipher-service
ENV CGO_ENABLED 0
ARG BUILD_REF

# Create the cmd directory and the copy the module files first and then
# download the dependencies. If this doesn't change, we won't need to do this
# again in future builds.
# RUN mkdir /cmd
# COPY go.* /cmd/
# WORKDIR /cmd
# RUN go mod download

# Copy the source code into the container.
COPY . /service

# Build the admin binary.
WORKDIR /service/app/tooling/sales-admin
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Build the cmd binary.
WORKDIR /cipher
RUN go build -ldflags "-X main.build=${BUILD_REF}"


# Run the Go Binary in Alpine.
FROM alpine:3.16
ARG BUILD_DATE
ARG BUILD_REF
RUN addgroup -g 1000 -S ciphers && \
    adduser -u 1000 -h /cipher -G ciphers -S ciphers
COPY --from=build_cipher-service --chown=ciphers:ciphers /cipher /cipher
WORKDIR /cipher
USER cipher
CMD ["./cipher"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="cipher-service" \
      org.opencontainers.image.authors="Adesina Hammed H. <delameh@icloud.com>" \
      org.opencontainers.image.source="https://github.com/cipher" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="Appital Inc."